db:
  url: jdbc:sqlite:/path/to/db.sqlite

credentials:
  username: "il_tuo_username"
  password: "la_tua_password"

discussion:
  author: "Nome Autore"
  title: "Titolo della discussione"
  text: |
    Testo della discussione su più righe se necessario.
    Puoi andare a capo e usare il blocco letterale.

apps:
  - 266840 # Age of Mythology: Extended Edition
  - 107100 # Bastion
  - 284160 # BeamNG.drive
  - 960990 # Beyond: Two Souls
  - 314830 # Blackguards 2
  - 1028310 # Book of Hours
  - 855740 # Bum Simulator
  - 204360 # Castle Crashers
#  - 255710 # Cities: Skylines
  - 718670 # Cultist Simulator
  - 262060 # Darkest Dungeon®
  - 700600 # Evil Genius 2
  - 304390 # For Honor
  - 323190 # Frostpunk
  - 222880 # Insurgency
  - 224900 # Iron Sky Invasion
  - 485510 # Nioh: Complete Edition
  - 233450 # Prison Architect
#  - 394310 # Punch Club
  - 340830 # Razenroth
  - 35450 # Rising Storm/Red Orchestra 2 Multiplayer
  - 300550 # Shadowrun: Dragonfall - Director's Cut
  - 289070 # Sid Meier's Civilization VI
  - 204880 # Sins of a Solar Empire: Rebellion
  - 485610 # Soccer Online: Ball 3D
  - 439190 # Stories: The Path of Destinies
  - 310950 # Street Fighter V
  - 264710 # Subnautica
  - 848450 # Subnautica: Below Zero
  - 286160 # Tabletop Simulator
  - 343860 # Tacoma
  - 1086860 # TOUHOU SKY ARENA MATSURI CLIMAX
  - 550370 # The Last Sin
  - 1515210 # The Past Within
  - 288160 # The Room
  - 425580 # The Room Two
  - 456750 # The Room Three
  - 1361320 # The Room 4: Old Sins

