db:
  url: jdbc:sqlite:/path/to/db.sqlite

credentials:
  username: "il_tuo_username"
  password: "la_tua_password"

discussion:
  author: "Nome Autore"
  title: "Titolo della discussione"
  text: |
    Testo della discussione su pi√π righe se necessario.
    Puoi andare a capo e usare il blocco letterale.

apps:
  - "570" # App1
  - "730" # App2
  - "123456" # App3
