[versions]
org-seleniumhq-selenium-selenium-java = "4.38.0"
ch-qos-logback-logback-classic  = "1.5.6"
com-sksamuel-hoplite = "1.4.16"
org-jetbrains-exposed = "0.46.0"
org-xerial-sqlite-jdbc = "3.44.1.0"

[libraries]
org-seleniumhq-selenium-selenium-java = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "org-seleniumhq-selenium-selenium-java" }
ch-qos-logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback-logback-classic"}
com-sksamuel-hoplite-hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "com-sksamuel-hoplite" }
com-sksamuel-hoplite-hoplite-yaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "com-sksamuel-hoplite" }
org-jetbrains-exposed-exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "org-jetbrains-exposed" }
org-jetbrains-exposed-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "org-jetbrains-exposed" }
org-jetbrains-exposed-exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "org-jetbrains-exposed" }
org-xerial-sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "org-xerial-sqlite-jdbc"}
